# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`
# monitors
monitor =eDP-1,1920x1080,0x0,1 
monitor =DP-5,3840x2160,1920x0,1.5
cursor {
    no_hardware_cursors = true
}

input {
    kb_layout = "de"
    kb_variant =
    kb_options = caps:swapescape
}